config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :guests
  resources :dinners
  get "add_input" => "dinners#add_input"
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_attachment :guest_photo
  has_many :dinner_guests, dependent: :destroy
  has_many :dinners, through: :dinner_guests
  belongs_to :user
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  def new
    @guest = Guest.new
  end
  def index
    @guests = Guest.where(user: current_user)
  end
  def create
    @guest = Guest.new(guest_params)
    @guest.user = current_user
    if @guest.save
           redirect_to guests_path, notice: 'Guest successfully saved !'
    else
            render :new
    end
  end

  def edit
    @guest = Guest.find(params[:id].to_i)
  end
  
  def show
    guest = Guest.find(params[:id].to_i)
    @guest_recipes = []
    if guest.user == current_user
      #prepare a list on recipes that will be manipulated inn the view to avoid duplicates
      if guest.dinners
        guest.dinners.each  do |dinner|
          if dinner.recipes
            dinner.recipes.each do |recipe|
              @guest_recipes << recipe
            end
          end
        end
      end
      @guest = guest
    else
      redirect_to guests_path
    end
  end
  
  def update
    @guest = Guest.find(params[:id].to_i)
    if @guest.user == current_user
      if @guest.update(guest_params)
        redirect_to @guest, notice: 'Guest successfully updated !'
      else
        render :edit
      end
    else
      redirect_to guests_path
    end
  end
  
  def destroy
    @guest = Guest.find(params[:id].to_i)
    if @guest.user == current_user
      if @guest.destroy
        redirect_to guests_path, alert: 'Guest successfully deleted !'
      else
        render :show
      end
    else
      redirect_to guests_path
    end
  end

private
# Using a private method to encapsulate the permissible parameters is
# a good pattern since you'll be able to reuse the same permit
# list between create and update. Also, you can specialize this method
# with per-user checking of permissible attributes.
  def guest_params
    params.require(:guest).permit(:first_name, :last_name, :guest_photo, :user, :likes_and_dislikes)
  end

end

app/views/guests/_form.html.erb
<%= simple_form_for @guest do |form| %>
    <%= form.input :first_name, label: "First name", placeholder: "John" %>
    <%= form.input :last_name, label: "Last name", placeholder: "Doe", error: 'Last name is mandatory, please specify one' %>
    <%= form.input :likes_and_dislikes, label: "Likes & Dislikes", placeholder: "Likes : chocolate, cheese and pizza / Dislikes : coliflower, organs and shellfish" %>
    <%= form.input :guest_photo, as: :attachinary %>
    <%= form.button :submit, class: "btn btn-primary", method: :post %>
    <%= link_to "Cancel", guests_path, class:"btn btn-default" %>
  <% end %>

app/views/guests/edit.html.erb
<div class="container">
  <div class="row  col-xs-offset-1">
    <div class = "container" "text-center">
      <h1>
          Edit guest
      </h1>
      <%= render "form" %>
    </div>

  </div>
</div>

app/views/guests/index.html.erb
<div class="container">
  <div class="row  col-xs-12 col-md-9 col-md-offset-1">
    <h1> All guests </h1>
    
    <% @guests.each do |guest| %>
      <div class="product">
        <!--<div class='product-upvote'>
          <div class="product-arrow"></div>
          <div class='product-count'>0</div>
        </div>-->
        <% if guest.guest_photo? %>
          <%= cl_image_tag guest.guest_photo.path, class: "product-image hidden-xs" %>
        <% else %>
          <img src="guest.jpg" class="product-image hidden-xs">
        <% end %>
        <div class='product-body'>
          <h3><%= link_to guest.first_name + " " + guest.last_name, guest_path(guest) %></h3>
        </div>
        <ul class="list-inline hidden-sm hidden-xs">
          <li>
            <%= link_to guest_path(guest) do %>
              <i class="fa fa-eye"></i>
            <% end %>
          </li>
          <li>
            <%= link_to edit_guest_path(guest) do %>
              <i class="fa fa-pencil"></i>
            <% end %>
          </li>
          <li>
            <%= link_to guest_path(guest), method: :delete do %>
              <i class="fa fa-trash"></i>
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/guests/new.html.erb
<div class="container">
  <div class="row  col-xs-offset-1">
    <div class = "container" "text-center">
      <h1>
          New guest
      </h1>
      <%= render "form" %>
    </div>

  </div>
</div>

app/views/guests/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://kitt.lewagon.com/placeholder/cities/berlin');">
  <div class="banner-content">
    <h1><%= @guest.first_name + " " + @guest.last_name%></h1>
    <% if @guest.guest_photo? %>
      <%= cl_image_tag @guest.guest_photo.path, :width => 300, :height => 200 %>
    <% end %>
    <h2>Likes and Dislikes: </h2>
    <!--TODO : find a simple way to respect simple text formatting...-->
    <p><%= @guest.likes_and_dislikes.gsub('\n', '<br>') %></p>
    <h3>you had this guest in the past : </h3>
    <% if @guest.dinners %>
      <% @guest.dinners.each do |dinner| %>
        <ul>
          <li> <%= link_to dinner.dinner_date, dinner_path(dinner) %> </li>
        </ul>
      <% end %>
    <% end %>
    <h3>and you served: </h3>
    <% if @guest_recipes %>
    <!--avoid duplicates in the recipe list-->
      <%@guest_recipes.uniq.each do |recipe| %>
        <ul>
          <li> <%= link_to recipe.name, recipe_path(recipe) %> </li>
        </ul>
      <%end%>
    <%end%>

    <%= link_to "Back", guests_path, class:"btn btn-default" %>
    <%= link_to "Edit", edit_guest_path(@guest), class:"btn btn-warning" %>
    <%= link_to "Delete", guest_path(@guest), method: :delete, class:"btn btn-danger" %>
  </div>
</div>