config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :guests
  resources :dinners
  get "add_input" => "dinners#add_input"
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_attachment :recipe_photo
  has_many :dinner_recipes, dependent: :destroy
  has_many :dinners, through: :dinner_recipes
  belongs_to :user
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def new
    @recipe = Recipe.new
  end
  def index
    @recipes = Recipe.where(user: current_user)
  end
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.save
      redirect_to recipes_path, notice: 'Recipe successfully saved !'
    else
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id].to_i)
  end
  
  def show
    recipe = Recipe.find(params[:id].to_i)
    if recipe.user == current_user
      @recipe = recipe
    else
      redirect_to recipes_path
    end
  end
  
  def update
    @recipe = Recipe.find(params[:id].to_i)
    if @recipe.user == current_user
      if @recipe.update(recipe_params)
        redirect_to recipes_path, notice: 'Recipe successfully updated !'
      else
        render :edit
      end
    else
      redirect_to recipes_path
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id].to_i)
    if @recipe.user == current_user
      if @recipe.destroy
        redirect_to recipes_path, alert: 'Recipe successfully deleted !'
      else
        render :show
      end
    else
      redirect_to recipes_path
    end
  end

private
# Using a private method to encapsulate the permissible parameters is
# a good pattern since you'll be able to reuse the same permit
# list between create and update. Also, you can specialize this method
# with per-user checking of permissible attributes.

  def recipe_params
    params.require(:recipe).permit(:name, :content, :recipe_photo, :user)
  end

end

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe do |form| %>
    <%= form.input :name, label: "recipe's title", placeholder: "Burger", error: 'Title is mandatory, please specify one' %>
    <%= form.input :content, label: "recipe", placeholder: "Place cheese and steak between buns" %>
    <%= form.input :recipe_photo, as: :attachinary %>
    <%= form.button :submit, class: "btn btn-primary", method: :post %>
    <%= link_to "Cancel", recipes_path, class:"btn btn-default" %>
    
  <% end %>

app/views/recipes/edit.html.erb
<div class="container">
  <div class="row  col-xs-offset-1">
    <div class = "container" "text-center">
      <h1>
          Edit Recipe
      </h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="container">
  <div class="row  col-xs-12 col-md-9 col-md-offset-1">
    <h1> All recipes </h1>
    
    <% @recipes.each do |recipe| %>
      <div class="product">
        <!--<div class='product-upvote'>
          <div class="product-arrow"></div>
          <div class='product-count'>0</div>
        </div>-->
        <% if recipe.recipe_photo? %>
          <%= cl_image_tag recipe.recipe_photo.path, class: "product-image hidden-xs" %>
        <% else %>
          <img src="recipe.jpg" class="product-image hidden-xs">
        <% end %>
        <div class='product-body'>
          <h3><%= link_to recipe.name, recipe_path(recipe) %></h3>
        </div>
        <ul class="list-inline hidden-sm hidden-xs">
          <li>
            <%= link_to recipe_path(recipe) do %>
              <i class="fa fa-eye"></i>
            <% end %>
          </li>
          <li>
            <%= link_to edit_recipe_path(recipe) do %>
              <i class="fa fa-pencil"></i>
            <% end %>
          </li>
          <li>
            <%= link_to recipe_path(recipe), method: :delete do %>
              <i class="fa fa-trash"></i>
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>

  </div>
</div>

app/views/recipes/new.html.erb
<div class="container">
  <div class="row  col-xs-offset-1">
    <div class = "container" "text-center">
      <h1>
          New Recipe
      </h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://kitt.lewagon.com/placeholder/cities/berlin');">
  <div class="banner-content">
    <div class="container">
      <h1><%= @recipe.name %></h1>
      <% if @recipe.recipe_photo? %>
        <%= cl_image_tag @recipe.recipe_photo.path, :width => 300, :height => 200 %>
      <% end %>
      <p><%= @recipe.content %></p>
    </div>
    <div class="container">
      <%= link_to "Back", recipes_path, class:"btn btn-default" %>
      <%= link_to "Edit", edit_recipe_path(@recipe), class:"btn btn-warning" %>
      <%= link_to "Delete", recipe_path(@recipe), method: :delete, class:"btn btn-danger" %>
    </div>
  </div>
</div>