config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :guests
  resources :dinners
  get "add_input" => "dinners#add_input"
end

app/views/shared/_flashes.html.erb
<!-- This file is in `app/views/shared/_flashes.html.erb` -->

<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_form.htlm.erb
<%= simple_form_for @recipe do |form| %>
    <%= form.input :name, label: "recipe's title", placeholder: "Burger", error: 'Title is mandatory, please specify one' %>
    <%= form.input :content, label: "recipe", placeholder: "Place cheese and steak between buns" %>
    <%= form.button :submit, class: "btn btn-primary", method: :post %>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
    <%= image_tag "logo.png", class: "logo" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">
    <% if current_user %>

      <div class="navbar-wagon-item">
        <div class="dropdown">

        </div>
      </div>

      <div class="navbar-wagon-item">
        <div class="dropdown">

        </div>
      </div>

      <!-- Recipe dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <span class="dropdown-toggle navbar-wagon-link" id="recipe-menu" data-toggle="dropdown">
            Recipes <i class="fa fa-caret-down"></i>
          </span>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "List recipes", recipes_path %></li>
            <li><%= link_to "New recipe", new_recipe_path %></li>
          </ul>
        </div>
      </div>

      <!-- Guest dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <span class="dropdown-toggle navbar-wagon-link" id="guest-menu" data-toggle="dropdown">
            Guests <i class="fa fa-caret-down"></i>
          </span>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "List guests", guests_path %></li>
            <li><%= link_to "New guest", new_guest_path %></li>
          </ul>
        </div>
      </div>

      <!-- Dinners dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <span class="dropdown-toggle navbar-wagon-link" id="dinner-menu" data-toggle="dropdown">
            Dinners <i class="fa fa-caret-down"></i>
          </span>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li><%= link_to "List dinners", dinners_path %></li>
            <li><%= link_to "New dinner", new_dinner_path %></li>
          </ul>
        </div>
      </div>

      <!-- Profile picture with dropdown list -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <% if current_user.avatar %>
            <%= cl_image_tag current_user.avatar.path, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", data: {toggle: "dropdown"} %>
          <% else %>
            <img src="https://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
          <% end %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu" id="navbar-wagon-menu">
            <li><%= link_to "Edit profile", edit_user_registration_path %></li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </div>
    <% else %>
      <%= link_to "Log in", new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <%= link_to "Sign up", new_user_registration_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><%= link_to "List recipes", recipes_path %></li>
        <li><%= link_to "List dinners", dinners_path %></li>
        <li><%= link_to "List guests", guests_path %></li>
        <li><%= link_to "Edit profile", edit_user_registration_path %></li>
        <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
      </ul>
    </div>
  </div>
</div>