config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :recipes
  resources :guests
  resources :dinners
  get "add_input" => "dinners#add_input"
end

app/models/dinner.rb
class Dinner < ApplicationRecord
  belongs_to :user
  has_many :dinner_recipes, dependent: :destroy
  accepts_nested_attributes_for :dinner_recipes, allow_destroy: true#, reject_if: :recipe_clones
  has_many :recipes, through: :dinner_recipes
  has_many :dinner_guests, dependent: :destroy
  accepts_nested_attributes_for :dinner_guests, allow_destroy: true
  has_many :guests, through: :dinner_guests
end

app/controllers/dinners_controller.rb
class DinnersController < ApplicationController
  def new
    @dinner = Dinner.new
    @dinner.dinner_recipes.build
    @dinner.dinner_guests.build
    @recipes = Recipe.where(user: current_user)
    @guests = Guest.where(user: current_user)
  end

  def index
    @dinners = Dinner.where(user: current_user)
  end

  def create
    @dinner = Dinner.new(dinner_params)
    @dinner.user = current_user
    @recipes = Recipe.where(user: current_user)
    @guests = Guest.where(user: current_user)
    recipes = []
    guests = []
    @dinner.dinner_recipes.each do |recipe|
      recipes << recipe.recipe_id
    end
    @dinner.dinner_guests.each do |guest|
      guests << guest.guest_id
    end
   
    if recipes.uniq.length == recipes.length && guests.uniq.length == guests.length
      if @dinner.save
        redirect_to dinners_path, notice: 'Dinner successfully saved !'
      else
        render :new
      end
    else
      flash[:alert] = "You can't add twice the same recipe or guest to a dinner"
      render :new
    end
  end

  def edit
    @dinner = Dinner.find(params[:id].to_i)
    @recipes = Recipe.where(user: current_user)
    @guests = Guest.where(user: current_user)
  end

  def show
    dinner = Dinner.find(params[:id].to_i)
    if dinner.user == current_user
      @dinner = dinner
    else
      redirect_to dinners_path
    end
  end

  # -- TODO : protect against duplication... /!\ the solution used in create doesn't work here as you can't work with @dinner 
  # ('cause it contains the records found by .find and not an empty dinner) but need to work directly with dinner_params
  # that is impossible to enumerate and work on...
  def update
    @dinner = Dinner.find(params[:id].to_i)
    @dinner_recipes = DinnerRecipe.where(dinner_id: @dinner.id)
    @dinner_guests = DinnerGuest.where(dinner_id: @dinner.id)
    if @dinner.user == current_user
      if @dinner.update(dinner_params)
        redirect_to @dinner, notice: 'Recipe successfully updated !'
      else
        render :edit
      end
    else
      redirect_to dinners_path
    end
  end
  
  def destroy
    @dinner = Dinner.find(params[:id].to_i)
    if @dinner.user == current_user
      if @dinner.destroy
        redirect_to dinners_path, alert: 'Dinner successfully deleted !'
      else
        render :show
      end
    else
      redirect_to dinners_path
    end
  end

private
# Using a private method to encapsulate the permissible parameters is
# a good pattern since you'll be able to reuse the same permit
# list between create and update. Also, you can specialize this method
# with per-user checking of permissible attributes.

  def dinner_params
    params.require(:dinner).permit(:id, :dinner_date, :user_id, dinner_recipes_attributes: [:id, :recipe_id, :_destroy], dinner_guests_attributes: [:id, :guest_id, :_destroy])
  end


end

app/views/dinners/_form.html.erb
<%= simple_form_for @dinner do |form| %>
    <%= form.input :dinner_date, as: :date, start_year: Date.today.year - 120,
                              end_year: Date.today.year + 10,
                              order: [:day, :month, :year] %>

   
    <!--New Recipes-->

      <h3>Recipes</h3>
      <div>
        <%= form.nested_fields_for :dinner_recipes do |ff| %>
          <div class="flex-input">
            <%= ff.input :recipe_id, collection: @recipes, label: false, placeholder: "Burger" %>
            <%= ff.remove_nested_fields_link do %>
              <i class="fa fa-times circle-icon circle-icon-red"></i>
            <% end %>
            
          </div>
        <%end%>
        <%= form.add_nested_fields_link :dinner_recipes do %>
          <i class="fa fa-plus circle-icon circle-icon-blue"></i> Add a recipe
        <% end %>
      </div>
    <!--New Guests-->

      <h3>Guests</h3>
        <div class="flex-form-container">
          <%= form.add_nested_fields_link :dinner_guests do %>
            <i class="fa fa-plus circle-icon circle-icon-blue"></i>
          <% end %>

          <%= form.nested_fields_for :dinner_guests do |ff| %>
            <div class="flex-input">
              <%= ff.input :guest_id, collection: @guests, label: false, placeholder: "John Doe", :label_method => lambda { |guest| "#{guest.first_name} #{guest.last_name}" } %>
              <%= ff.remove_nested_fields_link do %>
                <i class="fa fa-times circle-icon circle-icon-red"></i>
              <% end %>
            </div>
          <%end%>
        </div>


    <%= form.button :submit, class: "btn btn-primary", method: :post %>
    <%= link_to "Cancel", dinners_path, class:"btn btn-default" %>
<% end %>

app/views/dinners/edit.html.erb
<div class="container">
  <div class="row  col-xs-offset-1">
    <div class = "container" "text-center">
      <h1>
          Edit dinner
      </h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/dinners/index.html.erb
<div class="container">
  <div class="row col-xs-12 col-md-9 col-md-offset-1">
    <h1> All dinners </h1>
    
    <% @dinners.each do |dinner| %>
      <div class="product">
        <!--<div class='product-upvote'>
          <div class="product-arrow"></div>
          <div class='product-count'>0</div>
        </div>-->
        <div class='product-body'>
          <h3><%= link_to dinner.dinner_date.strftime("%d/%m/%Y"), dinner_path(dinner) %></h3>
        </div>
        <ul class="list-inline hidden-sm hidden-xs">
          <li>
            <%= link_to dinner_path(dinner) do %>
              <i class="fa fa-eye"></i>
            <% end %>
          </li>
          <li>
            <%= link_to edit_dinner_path(dinner) do %>
              <i class="fa fa-pencil"></i>
            <% end %>
          </li>
          <li>
            <%= link_to dinner_path(dinner), method: :delete do %>
              <i class="fa fa-trash"></i>
            <% end %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/dinners/new.html.erb
<div class="container">
  <div class="row  col-xs-offset-1">
    <div class = "container" "text-center">
      <h1>
          New dinner
      </h1>
      <%= render "form" %>
    </div>
  </div>
</div>

app/views/dinners/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('/assets/background-67fa7dc4bc54cea1f8625d54f42e3bc427d79fec1a0d50995fc75159fb35d9b9.jpg');">
  <div class="banner-content">
    <h1><%= @dinner.dinner_date.strftime("%d/%m/%Y") %></h1>
    <h3>you served the following: </h3>
    <ul>
      <% @dinner.recipes.each do |recipe| %>
        <li align="left"><%= link_to recipe.name, recipe_path(recipe) %></li>
      <% end %>
    </ul>
    <h3>And enjoyed it with: </h3>
    <ul>
      <% @dinner.guests.each do |guest| %>
        <li align="left"><%= link_to guest.first_name + " " + guest.last_name, guest_path(guest) %></li>
      <% end %>
    </ul>
    <br>
    <%= link_to "Back", dinners_path, class:"btn btn-default" %>
    <%= link_to "Edit", edit_dinner_path(@dinner), class:"btn btn-warning" %>
    <%= link_to "Delete", dinner_path(@dinner), method: :delete, class:"btn btn-danger"%>
  </div>
</div>